// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR0WOE_tOQdxhDc-Wgkb-Tzij3U3D2YYk',
    appId: '1:465260763703:web:83da2400bbba3c15393db2',
    messagingSenderId: '465260763703',
    projectId: 'chatappflutter-6a6d3',
    authDomain: 'chatappflutter-6a6d3.firebaseapp.com',
    storageBucket: 'chatappflutter-6a6d3.appspot.com',
    measurementId: 'G-GMT6S22BC6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqYQ2OCpeYjQto5gWNGvJ8nVYTP3_XF0E',
    appId: '1:465260763703:android:b0f6e7f237aa82af393db2',
    messagingSenderId: '465260763703',
    projectId: 'chatappflutter-6a6d3',
    storageBucket: 'chatappflutter-6a6d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTO0W3T5es_2BAjsxSJO1YSrQVIiIvA2U',
    appId: '1:465260763703:ios:9bfd252c5a6f0af6393db2',
    messagingSenderId: '465260763703',
    projectId: 'chatappflutter-6a6d3',
    storageBucket: 'chatappflutter-6a6d3.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTO0W3T5es_2BAjsxSJO1YSrQVIiIvA2U',
    appId: '1:465260763703:ios:9bfd252c5a6f0af6393db2',
    messagingSenderId: '465260763703',
    projectId: 'chatappflutter-6a6d3',
    storageBucket: 'chatappflutter-6a6d3.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBR0WOE_tOQdxhDc-Wgkb-Tzij3U3D2YYk',
    appId: '1:465260763703:web:211e521ac8fb5d9c393db2',
    messagingSenderId: '465260763703',
    projectId: 'chatappflutter-6a6d3',
    authDomain: 'chatappflutter-6a6d3.firebaseapp.com',
    storageBucket: 'chatappflutter-6a6d3.appspot.com',
    measurementId: 'G-QFN7MG8CJH',
  );
}
